spring:
  datasource:
    url: ${DB_URL:jdbc:sqlserver://localhost:1434;databaseName=${DB_NAME:backend};encrypt=false;trustServerCertificate=true}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:${MSSQL_SA_PASSWORD:}}
  jpa:
    hibernate:
      ddl-auto: none
